'use strict';
let when = ['В будущем ', "После завтра ", "Летом "];
let where = ['в музее ', 'в Египте ', 'в селе ', 'в лесу '];
let which = ['красивый ', 'ленивый ', 'красный ', 'смешной '];
let who = ['говорящий конь ', 'летающий дом ', 'комар ', 'Винни Пух '];
let did = ['купил хлеб. ', "закукарекал. ", "убил. ", "съел мед. "];
let cameoutofit = ['Из этого вышел вкусный завтрак. ', 'Из этого вышло много каллорий. ', 'Из этого вышел ранний подъем. ', 'Из этого вышло преступление. '];
let peopleSaid = ['Люди сказали: "О, ужас!".', 'Люди сказали: "Замолчи!".', 'Люди сказали: "Спасибо!".', 'Люди сказали: "Сколько можно!".'];
let rand1 = Math.floor(Math.random() * when.length);
let phrase1 = when[rand1];
let rand2 = Math.floor(Math.random() * where.length);
let phrase2 = where[rand2];
let rand3 = Math.floor(Math.random() * which.length);
let phrase3 = which[rand3];
let rand4 = Math.floor(Math.random() * who.length);
let phrase4 = who[rand4];
let rand5 = Math.floor(Math.random() * did.length);
let phrase5 = did[rand5];
let rand6 = Math.floor(Math.random() * cameoutofit.length);
let phrase6 = cameoutofit[rand6];
let rand7 = Math.floor(Math.random() * peopleSaid.length);
let phrase7 = peopleSaid[rand7];
document.write(phrase1 + phrase2 + phrase3 + phrase4 + phrase5 + phrase6 + phrase7);